export const statusList = [ "Без статуса", "Нужно сделать", "В работе", "Тестирование", "Готово"]


export const cardList = [
    {   id:1,
        topic:"Web design",
        title: "Название задачи",
        date:"30.10.23",
        status: "Без статуса",
    },
    {   id:2,
        topic:"CopyWriting",
        title: "Название задачи",
        date:"30.10.23",
        status: "Без статуса",
    }, 
    {   id:3,
        topic:"Web design",
        title: "Название задачи",
        date:"30.10.23",
        status: "Без статуса",
    },
    {   id:4,
        topic:"Research",
        title: "Название задачи",
        date:"30.10.23",
        status: "Нужно сделать",
    },
    {   id:5,
        topic:"Web design",
        title: "Название задачи",
        date:"30.10.23",
        status: "Готово",
    },
    {   id:6,
        topic:"Web design",
        title: "Название задачи",
        date:"30.10.23",
        status: "Без статуса",
    },
    {   id:7,
        topic:"CopyWriting",
        title: "Название задачи",
        date:"30.10.23",
        status: "В работе",
    },
    {   id:8,
        topic:"Web design",
        title: "Название задачи",
        date:"30.10.23",
        status: "Без статуса",
    },
    {   id:9,
        topic:"Web design",
        title: "Название задачи",
        date:"30.10.23",
        status: "Без статуса",
    },
    {   id:10,
        topic:"Research",
        title: "Название задачи",
        date:"30.10.23",
        status: "Тестирование",
    }
]