export const light = {
  body: "#EAEEF6",
  orangeBg: "#FFE4C2",
  greenBg: "#B4FDD1",
  purpleBg: "#E9D4FF",
  greyBg: "#94A6BE",
  orangeText: "#FF6D00",
  greenText: "#06B16E",
  purpleText: "#9A48F1",
  greyText: "#FFFFFF",
  backgroundCard: "#ffffff",
  titleColorCard: "#000000",
  backgroundColorHeader: "#ffffff",
  userColor: "#565eef",
  headerPopUserSetBackground: "#ffffff",
  lightGreyText: "#94a6be",
  lightGreyBg: "#FFFFFF",
  //logo: "./images/logo.png",
  //popUserSetName: "#000",
};
export const dark = {
  body: "#151419",
  orangeText: "#FFE4C2",
  greenText: "#B4FDD1",
  purpleText: "#E9D4FF",
  greyText: "#94A6BE",
  orangeBg: "#FF6D00",
  greenBg: "#06B16E",
  purpleBg: "#9A48F1",
  greyBg: "transparent",
  backgroundCard: "#20202C",
  titleColorCard: "#FFFFFF",
  backgroundColorHeader: "#20202C",
  userColor: "#FFFFFF",
  headerPopUserSetBackground: "#202229",
  lightGreyText: "#20202C",
  lightGreyBg: "#94A6BE",
  //logo: "./images/logo_dark.png",
  //popUserSetName:"#FFFFFF"
};
